services:
  - type: web
    name: ai-surveillance-backend
    env: python
    region: singapore
    plan: free
    rootDir: SURVILENCE-SYSTEM-NEW_CODE-main/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DEBUG
        value: "false"
      - key: PYTHON_VERSION
        value: "3.12.0"
